### PR TITLE
UWP functionality added

### LINKED ISSUE #6: [Feature Request] Add UWP support
ITNOA

Please implement ContactsPlugin for UWP.

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Fixes #6 

Changes Proposed in this pull request:
- Basic functionality supported for UWP
- Add UWP unit testing project for test some primaries functionality

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Very cool! I am out of town currently until next week and can review it then :)

**Comment by jamesmontemagno** [comment]
Browsing through the code, the only thing I would request is the remove of additional dependencies such as 
 "AutoMapper": "5.1.1",
-    "Nito.AsyncEx": "3.0.1"

There doesn't seem to be a real need for these here and I prefer minimal if not zero dependencies in Plugins.

**Comment by soroshsabz** [comment]
Thanks for your replay, 

I agree with you to prefer minimal dependencies but I think reinvented wheel is a bad practice, so when I want to convert two similar semantic class to each other, using AutoMapper is very cool and cause to easy coding and maintainability enhancement. 

For Nito.AsyncEx I need to call some `async` method in synchronous mode so this library help to write code easier. but if you have better approach for doing this work I welcome to your suggestion.

Best regards

**Comment by jamesmontemagno** [comment]
I have created a new UWP branch that I can merge it into, but I will end up removing the dependencies before consider moving it into master, although I understand the reasons to bring in dependencies sometimes as I do it myself from time to time. I am out of town for a while so if you want to go through and update it without the dependencies that will help me in the short term to get it into the next alpha, else I will have to go through it next week.

**Comment by groege** [comment]
Hi, 
I really could use this too - any idea when this will be available?
Thanks!

**Comment by soroshsabz** [comment]
Hi again,

I removed Nito.AsyncEx dependency. did you can review this PR little faster?

thanks

**Pull request merged**
